language: generic
os: linux

install:
  - cd ci/
  - source texlive.sh
  - cd ..

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - /tmp/tlpkg
    - doc/latex/pgfplots/figures/expensiveexamples
    - doc/latex/pgfplots/gnuplot

addons:
  apt:
    packages:
      - &base_deps
        - gnuplot
        - realpath

before_script:
  - git fetch --unshallow --tags
  - bash scripts/pgfplots/pgfplotsrevisionfile.sh
  - cat tex/generic/pgfplots/pgfplots.revision.tex

_build_manual: &_build_manual |
  set -e
  cd doc/latex/pgfplots
  while : ; do
    make -j $(nproc) LATEX="$engine -shell-escape -halt-on-error -interaction=nonstopmode"
    grep -q -E "(There were undefined references|Rerun to get (cross-references|the bars) right)" *.log || break
    [ "$(( thisrun=$(( thisrun + 1 )) ))" -lt 5 ] || { echo "Reruns exceeded"; exit 1; }
  done
  cd -

_build_package: &_build_package |
  set -e
  mkdir -pv /tmp/gh-pages
  cp -v doc/latex/pgfplots/*.pdf /tmp/gh-pages
  make -C .. -f pgfplots/scripts/pgfplots/Makefile.pgfplots_release_sourceforge

# FIXME:
# Currently none of the testsuites work. Therfore `make' is followed by `true'
# to set the exit status of the pipe to true. This has to be fixed to make this
# actually usable, because right now this will just always pass.
_build_tests: &_build_tests |
  cd "source/latex/pgfplots/pgfplotstest/$suite"
  make -j $(nproc) -k || true
  grep -A2 '^!' *.log

jobs:
  include:
    - name: Manual lualatex
      env: engine=lualatex
      script: *_build_manual
      after_success: *_build_package

    - name: Manual pdflatex
      env: engine=pdflatex
      script: *_build_manual
      after_success: *_build_package

    - name: Gallery
      script: |
        cd "doc/latex/pgfplots/gallery"
        make -j $(nproc) -k
        grep -A2 '^!' *.log

#   - name: lua_tests
#     env: suite=lua_tests
#     addons: {apt: {packages: [*base_deps, lua5.2, lua-unit]}}
#     script: *_build_tests

    - name: regressiontests
      env: suite=regressiontests
      addons: {apt: {packages: [*base_deps, imagemagick]}}
      script: *_build_tests

    - name: unittest
      env: suite=unittest
      script: *_build_tests

deploy:
  - provider: pages
    skip_cleanup: true
    token: $GH_TOKEN
    committer_from_gh: true
    local_dir: /tmp/gh-pages
    on:
      branch: master
      tags: false
      condition: $engine = lualatex
  - provider: releases
    skip_cleanup: true
    token: $GH_TOKEN
    file_glob: true
    file:
      - ../pgfplots_*
    overwrite: true
    on:
      tags: true
      condition: $engine = lualatex
